/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modul2;

import javax.swing.JOptionPane;

/**
 *
 * @author Mutia
 */
public class Warung extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Warung.class.getName());

    /**
     * Creates new form Warung
     */
    public Warung() {
        initComponents();
        rdgCaraBayar.add(rdoCash);
        rdgCaraBayar.add(rdoBCA);
        rdgCaraBayar.add(rdoMandiri);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgCaraBayar = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chkSoto = new javax.swing.JCheckBox();
        chkSate = new javax.swing.JCheckBox();
        chkEsJeruk = new javax.swing.JCheckBox();
        chkEsTeh = new javax.swing.JCheckBox();
        txtSoto = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtEsJeruk = new javax.swing.JTextField();
        txtEsTeh = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rdoCash = new javax.swing.JRadioButton();
        rdoBCA = new javax.swing.JRadioButton();
        rdoMandiri = new javax.swing.JRadioButton();
        lblCaraBayar = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnKosong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("MENU");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("QUANTITY");

        chkSoto.setText("Soto : Rp.5000");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        chkSate.setText("Sate : Rp. 10000");
        chkSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateActionPerformed(evt);
            }
        });

        chkEsJeruk.setText("Es Jeruk : Rp. 2000");
        chkEsJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsJerukActionPerformed(evt);
            }
        });

        chkEsTeh.setText("Es Teh : Rp. 1500");
        chkEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsTehActionPerformed(evt);
            }
        });

        txtSoto.setEditable(false);
        txtSoto.setText("0");
        txtSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSotoActionPerformed(evt);
            }
        });

        txtSate.setEditable(false);
        txtSate.setText("0");

        txtEsJeruk.setEditable(false);
        txtEsJeruk.setText("0");

        txtEsTeh.setEditable(false);
        txtEsTeh.setText("0");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Cara Bayar");

        rdoCash.setSelected(true);
        rdoCash.setText("Cash");
        rdoCash.setActionCommand("Uang Cash");

        rdoBCA.setText("BCA Card");
        rdoBCA.setActionCommand("Kartu Debit BCA");

        rdoMandiri.setText("Mandiri Card");
        rdoMandiri.setActionCommand("Kartu Kredit Mandiri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rdoCash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rdoBCA, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addComponent(rdoMandiri))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoBCA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoMandiri)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblCaraBayar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCaraBayar.setText("CARA BAYAR");

        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblTotal.setText(" Rp.0-");

        btnKosong.setText("Kosongan");
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCaraBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkSoto)
                            .addComponent(chkSate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkEsJeruk, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(chkEsTeh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(79, 79, 79))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkSoto)
                            .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkSate)
                            .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkEsJeruk)
                            .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkEsTeh)
                            .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnHitung)
                        .addGap(29, 29, 29)
                        .addComponent(lblTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKosong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCaraBayar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        // TODO add your handling code here:
        if(chkSoto.isSelected()){
            txtSoto.setEditable(true);
            txtSoto.setText("1");
        }else{
            txtSoto.setEditable(false);
            txtSoto.setText("0");
        }
    }//GEN-LAST:event_chkSotoActionPerformed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:
        chkSoto.setSelected(false);
        chkSate.setSelected(false);
        chkEsJeruk.setSelected(false);
        chkEsTeh.setSelected(false);
        txtSoto.setText("0");
        txtSate.setText("0");
        txtEsJeruk.setText("0");
        txtEsTeh.setText("0");
        txtSoto.setEditable(false);
        txtSate.setEditable(false);
        txtEsJeruk.setEditable(false);
        txtEsTeh.setEditable(false);
        rdoCash.setSelected(true);
        lblTotal.setText("Rp. ");
        lblCaraBayar.setText("Cara Bayar ");
    }//GEN-LAST:event_btnKosongActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        // TODO add your handling code here:
        if(chkSate.isSelected()){
            txtSate.setEditable(true);
            txtSate.setText("1");
        }else{
            txtSate.setEditable(false);
            txtSate.setText("0");
        }
    }//GEN-LAST:event_chkSateActionPerformed

    private void chkEsJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsJerukActionPerformed
        // TODO add your handling code here:
        if(chkEsJeruk.isSelected()){
            txtEsJeruk.setEditable(true);
            txtEsJeruk.setText("1");
        }else{
            txtEsJeruk.setEditable(false);
            txtEsJeruk.setText("0");
        }
    }//GEN-LAST:event_chkEsJerukActionPerformed

    private void chkEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsTehActionPerformed
        // TODO add your handling code here:
        if(chkEsTeh.isSelected()){
            txtEsTeh.setEditable(true);
            txtEsTeh.setText("1");
        }else{
            txtEsTeh.setEditable(false);
            txtEsTeh.setText("0");
        }
    }//GEN-LAST:event_chkEsTehActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
         boolean IDataOke = true;

        if (chkSoto.isSelected() && txtSoto.getText() == " ") {
            IDataOke = false;
        }
        if (chkSate.isSelected() && txtSate.getText() == " ") {
            IDataOke = false;
        }
        if (chkEsJeruk.isSelected() && txtEsJeruk.getText() == " ") {
            IDataOke = false;
        }
        if (chkEsTeh.isSelected() && txtEsTeh.getText() == " ") {
            IDataOke = false;
        }

        if (!IDataOke) {
            JOptionPane.showMessageDialog(this,
                    "Data Dilengkapi dahulu");
        } else {

          
            int nSoto = Integer.parseInt(txtSoto.getText());
            int nSate = Integer.parseInt(txtSate.getText());
            int nEsJeruk = Integer.parseInt(txtEsJeruk.getText());
            int nEsTeh = Integer.parseInt(txtEsTeh.getText());

        
            int nTotal = (10000 * nSoto)
                    + (10000 * nSate) + (4000 * nEsJeruk) + (2000 * nEsTeh);
            lblTotal.setText("Rp. " + nTotal);

           
            if (rdoCash.isSelected()) {
                lblCaraBayar.setText(rdoCash.getActionCommand());
            }
            if (rdoBCA.isSelected()) {
                lblCaraBayar.setText(rdoBCA.getActionCommand());
            }
            if (rdoMandiri.isSelected()) {
                lblCaraBayar.setText(rdoMandiri.getActionCommand());
            }   
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Warung().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKosong;
    private javax.swing.JCheckBox chkEsJeruk;
    private javax.swing.JCheckBox chkEsTeh;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCaraBayar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.ButtonGroup rdgCaraBayar;
    private javax.swing.JRadioButton rdoBCA;
    private javax.swing.JRadioButton rdoCash;
    private javax.swing.JRadioButton rdoMandiri;
    private javax.swing.JTextField txtEsJeruk;
    private javax.swing.JTextField txtEsTeh;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    // End of variables declaration//GEN-END:variables
}
